language: node_js
node_js:
  - 10

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - echo "environment for MY_NAME=$MY_NAME"

script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node "$DOCKER_USERNAME"/simple-node-2:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/simple-node-2
